# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0
%define debug_package %{nil}
%if %{with bootstrap}
%global debug_package %{nil}
%endif

%global __go_gen_buildrequires 0
%global go_build_flags -mod=vendor

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/jad0s/libretalk
%global goipath         github.com/jad0s/libretalk
%global commit          2a3dc8b1f83162a96218a80ffa7d9e08fd26e4d0


# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
Self hosted, modular chat app.}

%global godocs          README.md

Name:           golang-github-jad0s-libretalk
Version:        0
Release:        %autorelease -p
Summary:        Self hosted, modular chat app

License:        # FIXME
URL:            %{gourl}
Source0:        https://github.com/jad0s/libretalk/archive/%{commit}.tar.gz

%description %{common_description}

%gopkg

%prep
%goprep -A
#%%autopatch -p1


%if %{without bootstrap}
%build
%gobuild -o %{gobuilddir}/bin/libretalk %{goipath}/cmd
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

#%%if %%{without bootstrap}
#%%if %%{with check}
#%%check
#export GO111MODULE=on
#export GOFLAGS="-mod=vendor"
#cd %%{_builddir}/libretalk-%%{commit}
#go test -v ./...
#%%endif
#%%endif

%if %{without bootstrap}
%files
#%%doc README.md
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should not use globs to avoid installing conflicting
# binaries.
# Write a _bindir line per each of the binaries the package will install.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%{_bindir}/*
%endif

%gopkgfiles

%changelog
%autochangelog
